// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

/**
 * @title IPoseidon
 * @notice Interface for Poseidon hash precompute contract (generated by circomlibjs)
 */
interface IPoseidon2 {
    function poseidon(uint256[2] calldata) external pure returns (uint256);
}

/**
 * @title PoseidonMerkleTree
 * @notice Incremental Merkle tree using Poseidon hash (matches circom circuits).
 * @dev Uses an external Poseidon hasher contract deployed from circomlibjs.
 *      Tree depth: 20 (~1M leaves).
 */
contract PoseidonMerkleTree {
    uint256 public constant TREE_DEPTH = 20;
    uint256 public constant MAX_LEAVES = 2 ** TREE_DEPTH;

    IPoseidon2 public immutable hasher;

    uint256 public nextLeafIndex;

    uint256[TREE_DEPTH] public zeros;
    uint256[TREE_DEPTH] public filledSubtrees;

    uint256 public currentRoot;

    uint256 public constant ROOT_HISTORY_SIZE = 100;
    uint256[100] public rootHistory;
    uint256 public currentRootIndex;
    mapping(uint256 => bool) public knownRoots;

    error MerkleTreeFull();

    constructor(address _hasher) {
        hasher = IPoseidon2(_hasher);

        // Precompute zero values using Poseidon
        uint256 zero = 0;
        zeros[0] = zero;
        filledSubtrees[0] = zero;

        for (uint256 i = 1; i < TREE_DEPTH; i++) {
            zero = _hashPair(zero, zero);
            zeros[i] = zero;
            filledSubtrees[i] = zero;
        }

        currentRoot = _hashPair(zero, zero);
        knownRoots[currentRoot] = true;
        rootHistory[0] = currentRoot;
    }

    function _insertLeaf(uint256 _leaf) internal returns (uint256 index) {
        if (nextLeafIndex >= MAX_LEAVES) revert MerkleTreeFull();

        index = nextLeafIndex;
        uint256 currentHash = _leaf;

        for (uint256 i = 0; i < TREE_DEPTH; i++) {
            if (index % 2 == 0) {
                filledSubtrees[i] = currentHash;
                currentHash = _hashPair(currentHash, zeros[i]);
            } else {
                currentHash = _hashPair(filledSubtrees[i], currentHash);
            }
            index /= 2;
        }

        currentRoot = currentHash;
        knownRoots[currentRoot] = true;

        currentRootIndex = (currentRootIndex + 1) % ROOT_HISTORY_SIZE;
        rootHistory[currentRootIndex] = currentRoot;

        nextLeafIndex++;
        return nextLeafIndex - 1;
    }

    function isKnownRoot(uint256 _root) public view returns (bool) {
        if (_root == currentRoot) return true;
        for (uint256 i = 0; i < ROOT_HISTORY_SIZE; i++) {
            if (rootHistory[i] == _root) return true;
        }
        return false;
    }

    function _hashPair(uint256 _left, uint256 _right) internal view returns (uint256) {
        return hasher.poseidon([_left, _right]);
    }
}
