// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/Pausable.sol";
import "./PoseidonMerkleTree.sol";

/**
 * @title IVerifier
 * @notice Interface for the Groth16 verifier generated by snarkjs
 */
interface IVerifier {
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[4] calldata _pubSignals
    ) external view returns (bool);
}

/**
 * @title ShieldedPoolV2
 * @notice Production privacy pool for qUSD with Groth16 ZK proof verification.
 *
 *  Uses Poseidon hash for both commitments AND Merkle tree (field-friendly,
 *  matches the circom circuit exactly).
 *
 *  Flow:
 *    1. commitment = Poseidon(secret, nullifier)  [off-chain]
 *    2. deposit(commitment, denomination)          [on-chain, Poseidon Merkle tree]
 *    3. Generate Groth16 proof of knowledge        [off-chain]
 *    4. withdraw(proof, root, nullifierHash, ...)  [on-chain]
 *
 *  Public signals (bound to proof):
 *    [0] root           — Poseidon Merkle root
 *    [1] nullifierHash  — Poseidon(nullifier)
 *    [2] recipient      — Withdrawal address
 *    [3] denomination   — Amount
 */
contract ShieldedPoolV2 is PoseidonMerkleTree, ReentrancyGuard, Ownable, Pausable {
    using SafeERC20 for IERC20;

    IERC20 public immutable token;
    IVerifier public immutable verifier;

    // --- Denominations ---

    mapping(uint256 => bool) public supportedDenominations;
    uint256[] public denominations;

    // --- Nullifiers ---

    mapping(uint256 => bool) public nullifierUsed;

    // --- Deposits ---

    mapping(uint256 => bool) public commitmentExists;
    uint256 public depositCount;

    // --- Relayer ---

    uint256 public relayerFeeBps = 50; // 0.5%
    uint256 public constant MAX_RELAYER_FEE = 500;
    uint256 public constant BASIS_POINTS = 10000;

    // --- Errors ---

    error InvalidDenomination(uint256 denomination);
    error DuplicateCommitment();
    error InvalidProof();
    error NullifierAlreadyUsed();
    error InvalidRoot();
    error InvalidRecipient();
    error FeeTooHigh();
    error DenominationAlreadyExists();

    // --- Events ---

    event DepositMade(
        uint256 indexed commitment,
        uint256 denomination,
        uint32 leafIndex,
        uint256 timestamp
    );
    event WithdrawalMade(
        address indexed recipient,
        uint256 indexed nullifierHash,
        address indexed relayer,
        uint256 denomination,
        uint256 fee
    );
    event DenominationAdded(uint256 denomination);

    constructor(address _token, address _verifier, address _hasher) Ownable(msg.sender) PoseidonMerkleTree(_hasher) {
        token = IERC20(_token);
        verifier = IVerifier(_verifier);

        // Default denominations (18 decimals)
        uint256[4] memory defaultDenoms = [
            uint256(100 * 1e18),
            uint256(1000 * 1e18),
            uint256(10000 * 1e18),
            uint256(100000 * 1e18)
        ];

        for (uint256 i = 0; i < 4; i++) {
            supportedDenominations[defaultDenoms[i]] = true;
            denominations.push(defaultDenoms[i]);
        }
    }

    // =========================================================================
    // Deposit
    // =========================================================================

    /**
     * @notice Deposit qUSD into the shielded pool
     * @param _commitment Poseidon(secret, nullifier) — computed off-chain
     * @param _denomination Amount of qUSD (must be supported denomination)
     */
    function deposit(uint256 _commitment, uint256 _denomination) external nonReentrant whenNotPaused {
        if (!supportedDenominations[_denomination]) revert InvalidDenomination(_denomination);
        if (commitmentExists[_commitment]) revert DuplicateCommitment();

        // Insert into Poseidon Merkle tree
        uint32 leafIndex = uint32(_insertLeaf(_commitment));

        commitmentExists[_commitment] = true;
        depositCount++;

        token.safeTransferFrom(msg.sender, address(this), _denomination);

        emit DepositMade(_commitment, _denomination, leafIndex, block.timestamp);
    }

    // =========================================================================
    // Withdraw
    // =========================================================================

    /**
     * @notice Withdraw qUSD using a Groth16 proof
     * @param _pA Proof element A (2 uint256)
     * @param _pB Proof element B (2x2 uint256)
     * @param _pC Proof element C (2 uint256)
     * @param _root Merkle root
     * @param _nullifierHash Poseidon(nullifier)
     * @param _recipient Address to receive qUSD
     * @param _relayer Relayer address (zero if self-relaying)
     * @param _denomination Amount
     */
    function withdraw(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint256 _root,
        uint256 _nullifierHash,
        address _recipient,
        address _relayer,
        uint256 _denomination
    ) external nonReentrant whenNotPaused {
        if (_recipient == address(0)) revert InvalidRecipient();
        if (!supportedDenominations[_denomination]) revert InvalidDenomination(_denomination);
        if (nullifierUsed[_nullifierHash]) revert NullifierAlreadyUsed();
        if (!isKnownRoot(_root)) revert InvalidRoot();

        // Verify Groth16 proof
        uint[4] memory pubSignals = [
            _root,
            _nullifierHash,
            uint256(uint160(_recipient)),
            _denomination
        ];

        if (!verifier.verifyProof(_pA, _pB, _pC, pubSignals)) {
            revert InvalidProof();
        }

        // Mark nullifier used
        nullifierUsed[_nullifierHash] = true;

        // Calculate relayer fee
        uint256 fee = 0;
        if (_relayer != address(0)) {
            fee = (_denomination * relayerFeeBps) / BASIS_POINTS;
        }

        // Transfer
        token.safeTransfer(_recipient, _denomination - fee);
        if (fee > 0) {
            token.safeTransfer(_relayer, fee);
        }

        emit WithdrawalMade(_recipient, _nullifierHash, _relayer, _denomination, fee);
    }

    // =========================================================================
    // Admin
    // =========================================================================

    function addDenomination(uint256 _denomination) external onlyOwner {
        if (supportedDenominations[_denomination]) revert DenominationAlreadyExists();
        supportedDenominations[_denomination] = true;
        denominations.push(_denomination);
        emit DenominationAdded(_denomination);
    }

    function setRelayerFee(uint256 _feeBps) external onlyOwner {
        if (_feeBps > MAX_RELAYER_FEE) revert FeeTooHigh();
        relayerFeeBps = _feeBps;
    }

    function pause() external onlyOwner { _pause(); }
    function unpause() external onlyOwner { _unpause(); }

    // =========================================================================
    // View
    // =========================================================================

    function getDenominations() external view returns (uint256[] memory) {
        return denominations;
    }

    function getPoolBalance() external view returns (uint256) {
        return token.balanceOf(address(this));
    }
}
